# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\Khang\Documents\GitHub\Debt-Calculation\ui\edit_store_infos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditStoreDialog(object):
    def setupUi(self, EditStoreDialog):
        EditStoreDialog.setObjectName("EditStoreDialog")
        EditStoreDialog.resize(480, 258)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditStoreDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(EditStoreDialog)
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(EditStoreDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.store_name = QtWidgets.QLineEdit(EditStoreDialog)
        self.store_name.setObjectName("store_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.store_name)
        self.label_8 = QtWidgets.QLabel(EditStoreDialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.store_phone = QtWidgets.QLineEdit(EditStoreDialog)
        self.store_phone.setObjectName("store_phone")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.store_phone)
        self.label_3 = QtWidgets.QLabel(EditStoreDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.store_addr = QtWidgets.QLineEdit(EditStoreDialog)
        self.store_addr.setObjectName("store_addr")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.store_addr)
        self.label_4 = QtWidgets.QLabel(EditStoreDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.store_street = QtWidgets.QLineEdit(EditStoreDialog)
        self.store_street.setObjectName("store_street")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.store_street)
        self.label_5 = QtWidgets.QLabel(EditStoreDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.store_dist = QtWidgets.QLineEdit(EditStoreDialog)
        self.store_dist.setObjectName("store_dist")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.store_dist)
        self.label_6 = QtWidgets.QLabel(EditStoreDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.store_province = QtWidgets.QLineEdit(EditStoreDialog)
        self.store_province.setObjectName("store_province")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.store_province)
        self.label_7 = QtWidgets.QLabel(EditStoreDialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.store_city = QtWidgets.QLineEdit(EditStoreDialog)
        self.store_city.setObjectName("store_city")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.store_city)
        self.verticalLayout.addLayout(self.formLayout)
        self.dialogButtonBox = QtWidgets.QDialogButtonBox(EditStoreDialog)
        self.dialogButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.dialogButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.dialogButtonBox.setObjectName("dialogButtonBox")
        self.verticalLayout.addWidget(self.dialogButtonBox)

        self.retranslateUi(EditStoreDialog)
        self.dialogButtonBox.accepted.connect(EditStoreDialog.accept) # type: ignore
        self.dialogButtonBox.rejected.connect(EditStoreDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditStoreDialog)

    def retranslateUi(self, EditStoreDialog):
        _translate = QtCore.QCoreApplication.translate
        EditStoreDialog.setWindowTitle(_translate("EditStoreDialog", "Dialog"))
        self.label.setText(_translate("EditStoreDialog", "# Store infomations:"))
        self.label_2.setText(_translate("EditStoreDialog", "Name"))
        self.label_8.setText(_translate("EditStoreDialog", "Phone"))
        self.label_3.setText(_translate("EditStoreDialog", "Address"))
        self.label_4.setText(_translate("EditStoreDialog", "Street"))
        self.label_5.setText(_translate("EditStoreDialog", "District"))
        self.label_6.setText(_translate("EditStoreDialog", "Province"))
        self.label_7.setText(_translate("EditStoreDialog", "City"))
